data:
  target: utils.data.FFHQ
  params:
    root: ~/data/FFHQ/images1024x1024
    image_size: 256


latent:
  target: utils.data.LatentDataset
  params:
    root: ./data/ffhq256-latents


dataloader:
  num_workers: 16
  pin_memory: true
  prefetch_factor: 2


model:
  target: models.unet.UNet
  params:
    input_size: 32
    in_channels: 4
    out_channels: 4
    dim: 128
    dim_mults: [1, 2, 2, 2]
    use_attn_size: [16, ]
    num_res_blocks: 2
    num_heads: 1
    dropout: 0.0


autoencoder:
  target: models.autoencoders.sdvae.SDVAE
  params: {}


encoder:
  target: models.encoders.dinov2.DINOv2Encoder
  params:
    layers:
      - blocks.1
      - blocks.3
      - blocks.5
      - blocks.7
      - blocks.9
      - norm
    global_stat: true
    patch2_stat: true
    patch4_stat: true


drifting:
  kernel_temp: [0.02, 0.05, 0.2]
  kernel_norm: mutual-softmax
  normalize_feature: true
  normalize_drift: true


train:
  num_steps: 400000

  num_groups: 1
  num_real_samples: 128
  num_fake_samples: 128

  ema_decay: 0.999
  clip_grad_norm: 2.0

  print_freq: 100
  save_freq: 10000
  sample_freq: 2000

  optim:
    target: torch.optim.AdamW
    params:
      lr: 5e-5
      betas: [0.9, 0.95]
      weight_decay: 0.01

  sched:
    target: utils.scheduler.CosineWarmupLR
    params:
      warmup_steps: 20000
      training_steps: 400000
